#!/bin/sh

echo 'Installing...'

vundleFolder=~/.vim/bundle/Vundle.vim/

# install vundle if is not intalled
if [ ! -d $vundleFolder ]; then
    git clone https://github.com/gmarik/Vundle.vim.git $vundleFolder
fi

# bakcup old vimrc
echo "Copying new vimc..."
mv ~/.vimrc ~/.vimrc.bpk

# install new vimrc
cp ./.vimrc ~/.vimrc

# update plugins
echo 'Installing plugins...'
vim -c VundleUpdate -c quitall

echo 'Finished.'
