#!/bin/sh

echo 'Installing...'

# installing plug.vim
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# bakcup old vimrc
echo "Copying new vimrc..."
if [ -e ~/.vimrc ];then
  echo "Backing up current vim file"
  mv ~/.vimrc ~/.vimrc.bpk
fi

# install new vimrc
cp ./.vimrc ~/.vimrc

echo 'Installing plugins...'
vim -c PlugInstall -c quitall

echo 'Finished.'

